use scred_config::ConfigLoader;
use scred_http::logging;
use scred_mitm::mitm::config::Config;
use scred_mitm::mitm::proxy::ProxyServer;
use std::env;
use tracing::info;

fn print_help() {
    println!("scred-mitm - MITM proxy with policy-based secret handling");
    println!();
    println!("USAGE:");
    println!("    scred-mitm [OPTIONS]");
    println!();
    println!("OPTIONS:");
    println!("    -h, --help           Show this help message");
    println!("    --config             Show configuration file help");
    println!("    --generate-config    Generate example configuration file");
    println!("    --generate-certs     Generate CA certificate and key");
    println!();
    println!("ENVIRONMENT VARIABLES:");
    println!("    SCRED_MITM_LISTEN       Listen address (default: 0.0.0.0:8080)");
    println!("    SCRED_MITM_CA_CERT      Path to CA certificate file");
    println!("    SCRED_MITM_CA_KEY       Path to CA private key file");
    println!("    SCRED_LOG_LEVEL         Log level: trace, debug, info, warn, error");
    println!("    SCRED_LOG_FORMAT        Log format: text, json, pretty");
    println!("    SCRED_POLICY_SEED       Seed for placeholder generation");
    println!("    SCRED_CONFIG_FILE       Path to config file");
    println!();
    println!("POLICY SYSTEM:");
    println!("    The policy system handles both placeholder replacement and redaction.");
    println!("    Set secrets via environment variables matching patterns in config:");
    println!("        OPENAI_API_KEY=sk-xxx  ANTHROPIC_API_KEY=sk-yyy");
    println!();
    println!("TRAFFIC FILTERING:");
    println!("    Default-deny with allowed domains whitelist.");
    println!("    Configure via 'traffic.allowed-domains' in scred.yaml");
    println!();
    println!("EXAMPLES:");
    println!("    scred-mitm                          # Start with defaults");
    println!("    scred-mitm --generate-config > scred.yaml  # Generate config");
    println!("    SCRED_LOG_FORMAT=json scred-mitm    # JSON logging");
    println!();
    println!("CONFIGURATION FILE:");
    println!("    scred-mitm reads from: ./scred.yaml, ~/.scred/config.yaml, /etc/scred/config.yaml");
    println!("    Run 'scred-mitm --config' for configuration file format");
    println!();
}

fn print_config_help() {
    println!("CONFIGURATION FILE FORMAT (scred.yaml)");
    println!();
    println!("Create scred.yaml in current directory, ~/.scred/, or /etc/scred/");
    println!();
    println!("EXAMPLE:");
    println!("---");
    println!("policy:");
    println!("  enabled: true");
    println!("  seed: \"$SCRED_POLICY_SEED\"");
    println!("  providers:");
    println!("    - type: env");
    println!("      keys: [\"*_API_KEY\", \"*_SECRET\", \"*_TOKEN\"]");
    println!("  discovery:");
    println!("    enabled: true");
    println!("    port: 9998");
    println!("  defaults:");
    println!("    headers:");
    println!("      Authorization: replace    # Replace placeholders with secrets");
    println!("      \"*\": redact             # Redact all other headers");
    println!("    body:");
    println!("      request: redact");
    println!("      response: redact");
    println!();
    println!("scred-mitm:");
    println!("  listen:");
    println!("    port: 8080");
    println!("    address: \"0.0.0.0\"");
    println!("  ca-cert:");
    println!("    cert-path: ./data/ca-cert.pem");
    println!("    key-path: ./data/ca-key.pem");
    println!("  traffic:");
    println!("    mode: allow-list");
    println!("    allowed-domains:");
    println!("      - \"*.openai.com\"");
    println!();
}

fn generate_example_config() {
    let config = r#"
# SCRED MITM Proxy Configuration
# Generated by: scred-mitm --generate-config

# Policy Configuration
# Handles both placeholder replacement and secret redaction
policy:
  enabled: true
  seed: "${SCRED_POLICY_SEED}"
  
  # Secret providers - glob patterns match environment variables
  providers:
    - type: env
      keys: ["*_API_KEY", "*_SECRET", "*_TOKEN"]
  
  # Discovery API - containers fetch their placeholders
  # Endpoint: http://proxy:9998/placeholders
  discovery:
    enabled: true
    port: 9998
  
  # Default processing rules
  defaults:
    headers:
      Authorization: replace    # Replace placeholders with real secrets
      "X-Api-Key": replace
      "*": redact               # Redact detected secrets in other headers
    body:
      request: redact
      response: redact
    patterns:
      redact: ["*"]
      keep: []

# MITM Proxy Configuration
scred-mitm:
  listen:
    port: 8080
    address: "0.0.0.0"
     
  # CA certificate for TLS interception
  ca-cert:
    cert-path: ./data/ca-cert.pem
    key-path: ./data/ca-key.pem
     
  # Traffic filtering (default-deny)
  traffic:
    mode: allow-list
    allowed-domains:
      - "*"
      # Allow all by default - restrict in production!

  # Per-host policy overrides (optional)
  # Uncomment to customize behavior per domain:
  # hosts:
  #   "api.openai.com":
  #     headers:
  #       Authorization: replace
  #       "*": redact
  #   "*.anthropic.com":
  #     headers:
  #       "X-Api-Key": replace
   "#;
       println!("{}", config.trim());
   }

fn generate_certificates() -> anyhow::Result<()> {
    use scred_mitm::mitm::tls::CertificateGenerator;
    use std::path::Path;

    // Load config to get paths
    let mut config = load_mitm_config_from_file()?
        .unwrap_or_else(|| Config::load().unwrap_or_default());

    let ca_key_path = Path::new(&config.tls.ca_key);
    let ca_cert_path = Path::new(&config.tls.ca_cert);

    println!("Generating CA certificate...");
    println!("  Key:  {}", ca_key_path.display());
    println!("  Cert: {}", ca_cert_path.display());

    // Ensure parent directories exist
    if let Some(parent) = ca_key_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    if let Some(parent) = ca_cert_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    CertificateGenerator::generate_ca_if_missing(ca_key_path, ca_cert_path)?;

    println!();
    println!("CA certificate generated successfully!");
    println!();
    println!("To trust this certificate:");
    println!("  Linux:   sudo cp {} /usr/local/share/ca-certificates/ && sudo update-ca-certificates", ca_cert_path.display());
    println!("  macOS:   sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {}", ca_cert_path.display());

    Ok(())
}

fn load_mitm_config_from_file() -> anyhow::Result<Option<Config>> {
    let mut file_config = match ConfigLoader::load() {
        Ok(fc) => fc,
        Err(_) => return Ok(None),
    };

    ConfigLoader::validate(&mut file_config)?;

    if let Some(mitm_cfg) = file_config.scred_mitm {
        let mut config = Config::default();

        // Listen configuration
        if let Some(port) = mitm_cfg.listen.port {
            config.proxy.listen = format!("{}:{}", mitm_cfg.listen.address.as_deref().unwrap_or("0.0.0.0"), port);
        } else if let Some(addr) = &mitm_cfg.listen.address {
            config.proxy.listen = format!("{}:{}", addr, 8080u16);
        }

        // Upstream proxy configuration
        if let Some(upstream) = &mitm_cfg.upstream_proxy {
            if upstream.enabled {
                config.proxy.upstream_timeout = format!("{}s", upstream.pool.idle_timeout_secs);
            }
        }

        // TLS/CA configuration
        if let Some(ca_path) = &mitm_cfg.ca_cert.path {
            config.tls.ca_cert = ca_path.clone().into();
        }
        if let Some(key_path) = &mitm_cfg.ca_cert.key_path {
            config.tls.ca_key = key_path.clone().into();
        }

        // Traffic filtering
        config.traffic.enabled = mitm_cfg.traffic.enabled;
        config.traffic.allowed_domains = mitm_cfg.traffic.allowed_domains.clone();

        return Ok(Some(config));
    }

    Ok(None)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let args: Vec<String> = env::args().collect();

    // Help flags (before logging init)
    if args.contains(&"--help".to_string()) || args.contains(&"-h".to_string()) {
        print_help();
        return Ok(());
    }
    if args.contains(&"--config".to_string()) {
        print_config_help();
        return Ok(());
    }
    if args.contains(&"--generate-config".to_string()) {
        generate_example_config();
        return Ok(());
    }
    if args.contains(&"--generate-certs".to_string()) {
        return generate_certificates();
    }

    logging::init_from_env();

    // Load config from file if available
    let mut config = load_mitm_config_from_file()?
        .unwrap_or_else(|| Config::load().unwrap_or_default());

    // Apply environment overrides
    if let Ok(listen) = env::var("SCRED_MITM_LISTEN") {
        config.proxy.listen = listen;
    }
    if let Ok(ca_cert) = env::var("SCRED_CA_CERT") {
        config.tls.ca_cert = ca_cert.into();
    }
    if let Ok(ca_key) = env::var("SCRED_CA_KEY") {
        config.tls.ca_key = ca_key.into();
    }

    info!("scred-mitm starting");
    info!("Listening on {}", config.proxy.listen);

    // Load config file for policy
    let file_config = ConfigLoader::load().ok();

    // Initialize policy engine
    let policy = if let Some(ref fc) = file_config {
        scred_mitm::init_policy_from_config(fc)
    } else {
        None
    };

    // Start discovery server if policy is enabled
    if let Some(ref engine) = policy {
        if let Some(_updater) = engine.run_discovery() {
            info!("Discovery server started on port {}", engine.discovery_port());
        }
        info!("Policy: enabled");
    } else {
        info!("Policy: disabled");
    }

    // Generate CA if needed
    let ca_cert_path = Path::new(&config.tls.ca_cert);
    let ca_key_path = Path::new(&config.tls.ca_key);

    if !ca_cert_path.exists() || !ca_key_path.exists() {
        use scred_mitm::mitm::tls::CertificateGenerator;
        CertificateGenerator::generate_ca_if_missing(ca_key_path, ca_cert_path)?;
        info!("Generated CA certificate: {}", ca_cert_path.display());
    }

    let server = ProxyServer::new(&config, policy)?;
    server.run().await
}

use std::path::Path;
