//! SCRED Forward Proxy
//!
//! A forward proxy with policy support (placeholder replacement + redaction).
//! Sits between your application and an upstream service, processing requests/responses
//! through the policy engine.

use anyhow::{anyhow, Result};
use scred_config::ConfigLoader;
use scred_http::fixed_upstream::FixedUpstream;
use scred_http::logging;
use scred_http::OptimizedDnsResolverBuilder;
use scred_policy::PolicyEngine;
use std::env;
use std::sync::Arc;
use tokio::net::TcpListener;
use tracing::{info, warn};

mod policy_integration;
pub use policy_integration::init_policy_from_config;

fn print_help() {
    println!("scred-proxy - Forward proxy with policy support");
    println!();
    println!("USAGE:");
    println!("    scred-proxy [OPTIONS]");
    println!();
    println!("OPTIONS:");
    println!("    -h, --help           Show this help message");
    println!("    --config             Show configuration file help");
    println!("    --generate-config    Generate example configuration file");
    println!();
    println!("ENVIRONMENT VARIABLES:");
    println!("    SCRED_PROXY_UPSTREAM_URL    Upstream backend URL (required)");
    println!("    SCRED_PROXY_LISTEN_PORT     Listen port (default: 9999)");
    println!("    SCRED_LOG_LEVEL             Log level: trace, debug, info, warn, error");
    println!("    SCRED_LOG_FORMAT            Log format: text, json, pretty");
    println!();
    println!("EXAMPLES:");
    println!("    scred-proxy");
    println!("    SCRED_PROXY_UPSTREAM_URL=https://api.example.com scred-proxy");
    println!("    scred-proxy --generate-config > scred.yaml");
}

fn print_config_help() {
    println!("CONFIGURATION FILE FORMAT (scred.yaml)");
    println!();
    println!("Create scred.yaml in current directory, ~/.scred/, or /etc/scred/");
    println!();
    println!("EXAMPLE:");
    println!("---");
    println!("policy:");
    println!("  enabled: true");
    println!("  seed: \"$SCRED_POLICY_SEED\"");
    println!("  providers:");
    println!("    - type: env");
    println!("      keys: [\"*_API_KEY\", \"*_SECRET\"]");
    println!("  discovery:");
    println!("    enabled: true");
    println!("    port: 9998");
    println!("  defaults:");
    println!("    headers:");
    println!("      Authorization: replace");
    println!("      \"*\": redact");
    println!("    body:");
    println!("      request: redact");
    println!("      response: redact");
    println!();
    println!("scred-proxy:");
    println!("  listen:");
    println!("    port: 9999");
    println!("    address: \"0.0.0.0\"");
    println!("  upstream:");
    println!("    url: \"https://api.openai.com\"");
    println!();
}

fn generate_example_config() {
    let config = r#"
# SCRED Forward Proxy Configuration
# Generated by: scred-proxy --generate-config

# Policy Configuration
policy:
  enabled: true
  seed: "$SCRED_POLICY_SEED"
  
  # Secret providers
  providers:
    - type: env
      keys: ["*_API_KEY", "*_SECRET", "*_TOKEN"]
  
  # Discovery API for containers
  discovery:
    enabled: true
    port: 9998
  
  # Default processing rules
  defaults:
    headers:
      Authorization: replace    # Replace placeholders with secrets
      "X-Api-Key": replace
      "*": redact               # Redact all other headers
    body:
      request: redact
      response: redact
    patterns:
      redact: ["*"]
      keep: []

# Forward proxy configuration
scred-proxy:
  listen:
    port: 9999
    address: "0.0.0.0"
  
  upstream:
    url: "https://api.openai.com"
    timeout_secs: 30
"#;
    println!("{}", config.trim());
}

/// Simple proxy configuration
#[derive(Clone, Debug)]
pub struct ProxyConfig {
    listen_addr: String,
    listen_port: u16,
    upstream: FixedUpstream,
}

impl ProxyConfig {
    fn from_config_file() -> Result<Self> {
        let mut file_config = ConfigLoader::load()?;
        ConfigLoader::validate(&mut file_config)?;

        let proxy_cfg = file_config.scred_proxy.ok_or_else(|| {
            anyhow!(
                "No scred-proxy configuration found. \
                 Configure scred-proxy section in scred.yaml or set SCRED_PROXY_UPSTREAM_URL"
            )
        })?;

        let listen_port = proxy_cfg
            .listen
            .port
            .or_else(|| {
                env::var("SCRED_PROXY_LISTEN_PORT")
                    .ok()
                    .and_then(|p| p.parse().ok())
            })
            .unwrap_or(9999);

        let listen_addr = proxy_cfg
            .listen
            .address
            .unwrap_or_else(|| "0.0.0.0".to_string());

        let upstream_url = proxy_cfg
            .upstream
            .url
            .or_else(|| env::var("SCRED_PROXY_UPSTREAM_URL").ok())
            .ok_or_else(|| {
                anyhow!(
                    "Upstream URL required. \
                     Set 'scred_proxy.upstream.url' or SCRED_PROXY_UPSTREAM_URL"
                )
            })?;

        let upstream = FixedUpstream::parse(&upstream_url)?;

        info!(
            "Configuration loaded: listen={}:{}",
            listen_addr, listen_port
        );
        info!(
            "Upstream: {}://{}{}",
            upstream.scheme,
            upstream.authority(),
            upstream.base_path
        );

        Ok(Self {
            listen_addr,
            listen_port,
            upstream,
        })
    }

    fn from_env() -> Result<Self> {
        let listen_port = env::var("SCRED_PROXY_LISTEN_PORT")
            .unwrap_or_else(|_| "9999".to_string())
            .parse::<u16>()?;

        let upstream_url = env::var("SCRED_PROXY_UPSTREAM_URL")
            .map_err(|_| anyhow!("SCRED_PROXY_UPSTREAM_URL required when no config file found"))?;

        info!("Environment configuration: listen_port={}", listen_port);

        Ok(Self {
            listen_addr: "0.0.0.0".to_string(),
            listen_port,
            upstream: FixedUpstream::parse(&upstream_url)?,
        })
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let args: Vec<String> = env::args().collect();

    // Help flags (before logging init)
    if args.contains(&"--help".to_string()) || args.contains(&"-h".to_string()) {
        print_help();
        return Ok(());
    }
    if args.contains(&"--config".to_string()) {
        print_config_help();
        return Ok(());
    }
    if args.contains(&"--generate-config".to_string()) {
        generate_example_config();
        return Ok(());
    }

    logging::init_from_env();

    // Load config file for policy initialization
    let file_config = ConfigLoader::load().ok();

    // Initialize policy engine (starts discovery server if enabled)
    let policy: Option<Arc<PolicyEngine>> = if let Some(ref fc) = file_config {
        init_policy_from_config(fc)
    } else {
        None
    };

    // Start discovery server if policy is enabled
    if let Some(ref engine) = policy {
        if let Some(_updater) = engine.run_discovery() {
            info!(
                "Discovery server started on port {}",
                engine.discovery_port()
            );
        }
    }
    let config = ProxyConfig::from_config_file().or_else(|_| ProxyConfig::from_env())?;

    let listen_addr = format!("{}:{}", config.listen_addr, config.listen_port);

    info!("scred-proxy starting");
    info!("Listening on {}", listen_addr);
    info!(
        "Upstream: {}://{}{}",
        config.upstream.scheme,
        config.upstream.authority(),
        config.upstream.base_path
    );

    if policy.is_some() {
        info!("Policy: enabled (placeholder replacement + redaction)");
    } else {
        info!("Policy: disabled (forward-only mode)");
    }

    // DNS resolver with caching and pooling
    let resolver = Arc::new(
        OptimizedDnsResolverBuilder::new()
            .dns_ttl(60)
            .dns_enabled(true)
            .pool_size(10)
            .pool_timeout(30)
            .pool_enabled(true)
            .build(),
    );
    info!("DNS resolver: caching (60s), pooling (10 conns)");

    let config = Arc::new(config);
    let listener = TcpListener::bind(&listen_addr).await?;

    info!("Accepting connections");

    loop {
        let (stream, peer_addr) = listener.accept().await?;
        let config = Arc::clone(&config);
        let resolver = Arc::clone(&resolver);
        let policy_clone = policy.clone();

        tokio::spawn(async move {
            if let Err(e) =
                handler::handle_connection(stream, config, resolver, peer_addr, policy_clone).await
            {
                warn!("Connection error from {}: {}", peer_addr, e);
            }
        });
    }
}

/// Handle connection with policy processing
mod handler;
