//! SCRED Forward Proxy
//!
//! A forward proxy with policy support (placeholder replacement + redaction).
//! Sits between your application and an upstream service, processing requests/responses
//! through the policy engine.

use anyhow::{anyhow, Result};
use rustls::{ClientConfig, RootCertStore, ServerName};
use scred_config::ConfigLoader;
use scred_http::fixed_upstream::FixedUpstream;
use scred_http::logging;
use scred_http::{OptimizedDnsResolver, OptimizedDnsResolverBuilder};
use scred_policy::PolicyEngine;
use std::env;
use std::sync::Arc;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::net::{TcpListener, TcpStream};
use tokio_rustls::TlsConnector;
use tracing::{debug, info, warn};

mod policy_integration;
pub use policy_integration::init_policy_from_config;

fn print_help() {
    println!("scred-proxy - Forward proxy with policy support");
    println!();
    println!("USAGE:");
    println!("    scred-proxy [OPTIONS]");
    println!();
    println!("OPTIONS:");
    println!("    -h, --help           Show this help message");
    println!("    --config             Show configuration file help");
    println!("    --generate-config    Generate example configuration file");
    println!();
    println!("ENVIRONMENT VARIABLES:");
    println!("    SCRED_PROXY_UPSTREAM_URL    Upstream backend URL (required)");
    println!("    SCRED_PROXY_LISTEN_PORT     Listen port (default: 9999)");
    println!("    SCRED_LOG_LEVEL             Log level: trace, debug, info, warn, error");
    println!("    SCRED_LOG_FORMAT            Log format: text, json, pretty");
    println!();
    println!("EXAMPLES:");
    println!("    scred-proxy");
    println!("    SCRED_PROXY_UPSTREAM_URL=https://api.example.com scred-proxy");
    println!("    scred-proxy --generate-config > scred.yaml");
}

fn print_config_help() {
    println!("CONFIGURATION FILE FORMAT (scred.yaml)");
    println!();
    println!("Create scred.yaml in current directory, ~/.scred/, or /etc/scred/");
    println!();
    println!("EXAMPLE:");
    println!("---");
    println!("policy:");
    println!("  enabled: true");
    println!("  seed: \"$SCRED_POLICY_SEED\"");
    println!("  providers:");
    println!("    - type: env");
    println!("      keys: [\"*_API_KEY\", \"*_SECRET\"]");
    println!("  discovery:");
    println!("    enabled: true");
    println!("    port: 9998");
    println!("  defaults:");
    println!("    headers:");
    println!("      Authorization: replace");
    println!("      \"*\": redact");
    println!("    body:");
    println!("      request: redact");
    println!("      response: redact");
    println!();
    println!("scred-proxy:");
    println!("  listen:");
    println!("    port: 9999");
    println!("    address: \"0.0.0.0\"");
    println!("  upstream:");
    println!("    url: \"https://api.openai.com\"");
    println!();
}

fn generate_example_config() {
    let config = r#"
# SCRED Forward Proxy Configuration
# Generated by: scred-proxy --generate-config

# Policy Configuration
policy:
  enabled: true
  seed: "$SCRED_POLICY_SEED"
  
  # Secret providers
  providers:
    - type: env
      keys: ["*_API_KEY", "*_SECRET", "*_TOKEN"]
  
  # Discovery API for containers
  discovery:
    enabled: true
    port: 9998
  
  # Default processing rules
  defaults:
    headers:
      Authorization: replace    # Replace placeholders with secrets
      "X-Api-Key": replace
      "*": redact               # Redact all other headers
    body:
      request: redact
      response: redact
    patterns:
      redact: ["*"]
      keep: []

# Forward proxy configuration
scred-proxy:
  listen:
    port: 9999
    address: "0.0.0.0"
  
  upstream:
    url: "https://api.openai.com"
    timeout_secs: 30
"#;
    println!("{}", config.trim());
}

/// Simple proxy configuration
#[derive(Clone, Debug)]
struct ProxyConfig {
    listen_addr: String,
    listen_port: u16,
    upstream: FixedUpstream,
}

impl ProxyConfig {
    fn from_config_file() -> Result<Self> {
        let file_config = ConfigLoader::load()?;
        ConfigLoader::validate(&file_config)?;
        
        let proxy_cfg = file_config.scred_proxy.ok_or_else(|| {
            anyhow!(
                "No scred-proxy configuration found. \
                 Configure scred-proxy section in scred.yaml or set SCRED_PROXY_UPSTREAM_URL"
            )
        })?;

        let listen_port = proxy_cfg
            .listen
            .port
            .or_else(|| {
                env::var("SCRED_PROXY_LISTEN_PORT")
                    .ok()
                    .and_then(|p| p.parse().ok())
            })
            .unwrap_or(9999);

        let listen_addr = proxy_cfg
            .listen
            .address
            .unwrap_or_else(|| "0.0.0.0".to_string());

        let upstream_url = proxy_cfg
            .upstream
            .url
            .or_else(|| env::var("SCRED_PROXY_UPSTREAM_URL").ok())
            .ok_or_else(|| {
                anyhow!(
                    "Upstream URL required. \
                     Set 'scred_proxy.upstream.url' or SCRED_PROXY_UPSTREAM_URL"
                )
            })?;

        let upstream = FixedUpstream::parse(&upstream_url)?;

        info!("Configuration loaded: listen={}:{}", listen_addr, listen_port);
        info!(
            "Upstream: {}://{}{}",
            upstream.scheme, upstream.authority(), upstream.base_path
        );

        Ok(Self {
            listen_addr,
            listen_port,
            upstream,
        })
    }

    fn from_env() -> Result<Self> {
        let listen_port = env::var("SCRED_PROXY_LISTEN_PORT")
            .unwrap_or_else(|_| "9999".to_string())
            .parse::<u16>()?;

        let upstream_url =
            env::var("SCRED_PROXY_UPSTREAM_URL").map_err(|_| {
                anyhow!("SCRED_PROXY_UPSTREAM_URL required when no config file found")
            })?;

        info!("Environment configuration: listen_port={}", listen_port);

        Ok(Self {
            listen_addr: "0.0.0.0".to_string(),
            listen_port,
            upstream: FixedUpstream::parse(&upstream_url)?,
        })
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let args: Vec<String> = env::args().collect();

    // Help flags (before logging init)
    if args.contains(&"--help".to_string()) || args.contains(&"-h".to_string()) {
        print_help();
        return Ok(());
    }
    if args.contains(&"--config".to_string()) {
        print_config_help();
        return Ok(());
    }
    if args.contains(&"--generate-config".to_string()) {
        generate_example_config();
        return Ok(());
    }

    logging::init_from_env();

    // Load config file for policy initialization
    let file_config = ConfigLoader::load().ok();

    // Initialize policy engine (starts discovery server if enabled)
    let policy: Option<Arc<PolicyEngine>> = if let Some(ref fc) = file_config {
        init_policy_from_config(fc)
    } else {
        None
    };


    // Start discovery server if policy is enabled
    if let Some(ref engine) = policy {
        if let Some(_updater) = engine.run_discovery() {
            info!("Discovery server started on port {}", engine.discovery_port());
        }
    }    let config = ProxyConfig::from_config_file().or_else(|_| ProxyConfig::from_env())?;

    let listen_addr = format!("{}:{}", config.listen_addr, config.listen_port);

    info!("scred-proxy starting");
    info!("Listening on {}", listen_addr);
    info!(
        "Upstream: {}://{}{}",
        config.upstream.scheme,
        config.upstream.authority(),
        config.upstream.base_path
    );

    if policy.is_some() {
        info!("Policy: enabled (placeholder replacement + redaction)");
    } else {
        info!("Policy: disabled (forward-only mode)");
    }

    // DNS resolver with caching and pooling
    let resolver = Arc::new(
        OptimizedDnsResolverBuilder::new()
            .dns_ttl(60)
            .dns_enabled(true)
            .pool_size(10)
            .pool_timeout(30)
            .pool_enabled(true)
            .build(),
    );
    info!("DNS resolver: caching (60s), pooling (10 conns)");

    let config = Arc::new(config);
    let listener = TcpListener::bind(&listen_addr).await?;

    info!("Accepting connections");

    loop {
        let (stream, peer_addr) = listener.accept().await?;
        let config = Arc::clone(&config);
        let resolver = Arc::clone(&resolver);
        let policy_clone = policy.clone();

        tokio::spawn(async move {
            if let Err(e) =
                handle_connection(stream, config, resolver, peer_addr, policy_clone).await
            {
                warn!("Connection error from {}: {}", peer_addr, e);
            }
        });
    }
}

/// Handle connection with policy processing
async fn handle_connection(
    stream: TcpStream,
    config: Arc<ProxyConfig>,
    resolver: Arc<OptimizedDnsResolver>,
    peer_addr: std::net::SocketAddr,
    policy: Option<Arc<PolicyEngine>>,
) -> Result<()> {
    use tokio::io::copy;

    let (client_read, mut client_write) = stream.into_split();
    let mut client_reader = BufReader::with_capacity(256 * 1024, client_read);
    let mut request_count = 0;

    loop {
        request_count += 1;

        let mut first_line = String::new();
        client_reader.read_line(&mut first_line).await?;

        if first_line.is_empty() {
            if request_count > 1 {
                debug!("Connection closed after {} requests", request_count - 1);
            }
            break;
        }

        let first_line = first_line.trim().to_string();
        let request_path = extract_path(&first_line);

        info!(
            "{} \"{} {}\"",
            peer_addr.ip(),
            extract_method(&first_line),
            request_path
        );

        let upstream_addr = config.upstream.authority();
        let rewritten_request_line = config.upstream.rewrite_request_line(&first_line)?;

        let tcp_stream = resolver.connect_with_retry(&upstream_addr).await?;

        if config.upstream.scheme == "https" {
            let mut upstream = connect_tls_upstream(tcp_stream, &config.upstream.host).await?;

            // Forward request with policy processing
            if let Some(ref engine) = policy {
                forward_with_policy(
                    &mut client_reader,
                    &mut upstream,
                    &rewritten_request_line,
                    engine,
                    &config.upstream.host,
                )
                .await?;
            } else {
                // No policy - simple forwarding
                forward_simple(&mut client_reader, &mut upstream, &rewritten_request_line).await?;
            }

            // Read and forward response
            let mut upstream_buf = BufReader::new(upstream);
            copy(&mut upstream_buf, &mut client_write).await?;
        } else {
            let mut upstream = tcp_stream;

            if let Some(ref engine) = policy {
                forward_with_policy(
                    &mut client_reader,
                    &mut upstream,
                    &rewritten_request_line,
                    engine,
                    &config.upstream.host,
                )
                .await?;
            } else {
                forward_simple(&mut client_reader, &mut upstream, &rewritten_request_line).await?;
            }

            let mut upstream_buf = BufReader::new(upstream);
            copy(&mut upstream_buf, &mut client_write).await?;
        }

        client_write.flush().await?;
    }

    Ok(())
}

/// Forward request with policy processing
async fn forward_with_policy<R, W>(
    client_reader: &mut BufReader<R>,
    upstream: &mut W,
    request_line: &str,
    engine: &PolicyEngine,
    host: &str,
) -> Result<()>
where
    R: tokio::io::AsyncRead + Unpin,
    W: tokio::io::AsyncWrite + Unpin,
{
    // Send request line
    let req_line = format!("{}\r\n", request_line);
    upstream.write_all(req_line.as_bytes()).await?;

    // Read and process headers
    let mut headers = Vec::new();
    loop {
        let mut line = String::new();
        client_reader.read_line(&mut line).await?;
        if line == "\r\n" || line.is_empty() {
            break;
        }
        headers.push(line);
    }

    // Process headers through policy engine
    let header_str: String = headers.join("");
    let mut header_bytes = header_str.into_bytes();
    
    // Use placeholder automaton for replacement
    let automaton = engine.create_placeholder_automaton();
    let (_, count) = automaton.replace_placeholders(&mut header_bytes, host, |_, _| true);
    
    if count > 0 {
        debug!("Replaced {} placeholders in request headers", count);
    }

    upstream.write_all(&header_bytes).await?;
    upstream.write_all(b"\r\n").await?;
    upstream.flush().await?;

    Ok(())
}

/// Simple forwarding without policy
async fn forward_simple<R, W>(
    client_reader: &mut BufReader<R>,
    upstream: &mut W,
    request_line: &str,
) -> Result<()>
where
    R: tokio::io::AsyncRead + Unpin,
    W: tokio::io::AsyncWrite + Unpin,
{
    // Send request line
    let req_line = format!("{}\r\n", request_line);
    upstream.write_all(req_line.as_bytes()).await?;

    // Forward headers
    let mut headers_buf = Vec::new();
    loop {
        let mut line = String::new();
        client_reader.read_line(&mut line).await?;
        headers_buf.extend_from_slice(line.as_bytes());
        if line == "\r\n" || line.is_empty() {
            break;
        }
    }

    upstream.write_all(&headers_buf).await?;
    upstream.flush().await?;

    Ok(())
}

async fn connect_tls_upstream<S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin>(
    stream: S,
    host: &str,
) -> Result<tokio_rustls::client::TlsStream<S>> {
    let mut root_store = RootCertStore::empty();
    root_store.add_trust_anchors(webpki_roots::TLS_SERVER_ROOTS.iter().map(|ta| {
        rustls::OwnedTrustAnchor::from_subject_spki_name_constraints(
            ta.subject,
            ta.spki,
            ta.name_constraints,
        )
    }));

    let client_config = ClientConfig::builder()
        .with_safe_defaults()
        .with_root_certificates(root_store)
        .with_no_client_auth();

    let connector = TlsConnector::from(Arc::new(client_config));
    let server_name =
        ServerName::try_from(host).map_err(|_| anyhow!("Invalid upstream host: {}", host))?;

    connector
        .connect(server_name, stream)
        .await
        .map_err(|e| anyhow!("TLS handshake failed: {}", e))
}

fn extract_method(request_line: &str) -> &str {
    request_line.split(' ').next().unwrap_or("UNKNOWN")
}

fn extract_path(request_line: &str) -> &str {
    let parts: Vec<&str> = request_line.split(' ').collect();
    if parts.len() >= 2 {
        let path_with_query = parts[1];
        path_with_query.split('?').next().unwrap_or("/")
    } else {
        "/"
    }
}
