use super::{Charset, PatternTier, PrefixValidationPattern};

pub const PREFIX_VALIDATION_PATTERNS: &[PrefixValidationPattern] = &[
    PrefixValidationPattern {
        name: "1password-svc-token",
        prefix: "ops_eyJ",
        tier: PatternTier::Infrastructure,
        min_len: 250,
        max_len: 300,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "assertible",
        prefix: "assertible_",
        tier: PatternTier::Services,
        min_len: 20,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "atlassian",
        prefix: "AAAAA",
        tier: PatternTier::ApiKeys,
        min_len: 20,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "checkr-personal-access-token",
        prefix: "chk_live_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "circleci-personal-access-token",
        prefix: "ccpat_",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "contentful-personal-access-token",
        prefix: "CFPAT-",
        tier: PatternTier::ApiKeys,
        min_len: 43,
        max_len: 43,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "databricks-token",
        prefix: "dapi",
        tier: PatternTier::Infrastructure,
        min_len: 32,
        max_len: 200,
        charset: Charset::Hex,
    },
    PrefixValidationPattern {
        name: "digicert-api-key",
        prefix: "d7dc",
        tier: PatternTier::Services,
        min_len: 20,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "expo-access-token",
        prefix: "ExponentPushToken[",
        tier: PatternTier::Services,
        min_len: 60,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "figma-token",
        prefix: "figd_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "flutterwave",
        prefix: "FLWRSP_TEST_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "gandi-api-key",
        prefix: "Ov23li",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "generic-api-key",
        prefix: "X-API-KEY:",
        tier: PatternTier::Patterns,
        min_len: 20,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "gitee-access-token",
        prefix: "glpat-",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "github-token-detailed",
        prefix: "ghp_",
        tier: PatternTier::Critical,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "gitlab-token-detailed",
        prefix: "glpat-",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "google-gemini",
        prefix: "AIzaSy",
        tier: PatternTier::ApiKeys,
        min_len: 33,
        max_len: 33,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "grafana-api-key",
        prefix: "eyJrIjoiZWQ",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "heroku-api-key",
        prefix: "heroku_",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "hubspot-api-key",
        prefix: "pat-",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "huggingface-token",
        prefix: "hf_",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mailgun-api-key",
        prefix: "key-",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mapbox-token",
        prefix: "pk.",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mailchimp-api-key",
        prefix: "us",
        tier: PatternTier::ApiKeys,
        min_len: 32,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "minio-access-key",
        prefix: "minioadmin",
        tier: PatternTier::Infrastructure,
        min_len: 20,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "newrelic-api-key",
        prefix: "NRAK-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "npm-token",
        prefix: "npm_",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "noco-auth-token",
        prefix: "eyJhbGciOiJIUzI1N",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "notion-api-key",
        prefix: "secret_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "okta-token",
        prefix: "okta_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "pagerduty-api-key",
        prefix: "u+",
        tier: PatternTier::ApiKeys,
        min_len: 32,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "paypal-signature",
        prefix: "sig=",
        tier: PatternTier::Services,
        min_len: 50,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "postman-api-key",
        prefix: "PMAK-",
        tier: PatternTier::ApiKeys,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "pulumi-api-token",
        prefix: "pul-",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "sendbird-api-token",
        prefix: "SendBird.",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sendgrid-api-key",
        prefix: "SG.",
        tier: PatternTier::Services,
        min_len: 60,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "sentry-auth-token",
        prefix: "sntrys_eyJ",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "slack-bot-token",
        prefix: "xoxb-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slack-user-token",
        prefix: "xoxp-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "stripe-api-key-live",
        prefix: "sk_live_",
        tier: PatternTier::Critical,
        min_len: 32,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "stripe-api-key-test",
        prefix: "sk_test_",
        tier: PatternTier::Critical,
        min_len: 32,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "supabase-api-key",
        prefix: "eyJhbGciOiJIUzI1N",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "twilio-api-key",
        prefix: "AC",
        tier: PatternTier::Critical,
        min_len: 32,
        max_len: 34,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "telegram-bot-token",
        prefix: "bot",
        tier: PatternTier::Services,
        min_len: 24,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // ============================================================================
    // BATCH 1: TDD Implementation - 25 Core Patterns from test_cases.csv
    // ============================================================================
    // AWS (3 patterns)
    PrefixValidationPattern {
        name: "aws-access-token",
        prefix: "AKIA",
        tier: PatternTier::Critical,
        min_len: 20,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "aws-session-token",
        prefix: "ASIA",
        tier: PatternTier::Critical,
        min_len: 20,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "aws-secret-access-key",
        prefix: "aws-secret-access-key_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    // GitHub (5 patterns)
    PrefixValidationPattern {
        name: "github-pat",
        prefix: "ghp_",
        tier: PatternTier::Critical,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "github-oauth",
        prefix: "gho_",
        tier: PatternTier::Critical,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "github-user",
        prefix: "ghu_",
        tier: PatternTier::Critical,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "github-refresh",
        prefix: "ghr_",
        tier: PatternTier::ApiKeys,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "github-app-token",
        prefix: "ghs_",
        tier: PatternTier::ApiKeys,
        min_len: 36,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Slack (3 patterns)
    PrefixValidationPattern {
        name: "slack-bot-token",
        prefix: "xoxb-",
        tier: PatternTier::Critical,
        min_len: 50,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slack-user-token",
        prefix: "xoxp-",
        tier: PatternTier::Critical,
        min_len: 50,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slackwebhook",
        prefix: "slackwebhook_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    // Stripe (3 patterns)
    PrefixValidationPattern {
        name: "stripe",
        prefix: "stripe_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "stripepaymentintent",
        prefix: "stripepaymentintent_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "stripepaymentintent-1",
        prefix: "stripepaymentintent-1_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    // Google (2 patterns)
    PrefixValidationPattern {
        name: "googlegemini",
        prefix: "googlegemini_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "googleoauth2",
        prefix: "googleoauth2_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    // Azure (3 patterns)
    PrefixValidationPattern {
        name: "azure-ad-client-secret",
        prefix: "azure-ad-client-secret_",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "azure_storage",
        prefix: "azure_storage_",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "azurefunctionkey",
        prefix: "azurefunctionkey_",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    // OpenAI (1 pattern)
    PrefixValidationPattern {
        name: "anthropic",
        prefix: "anthropic_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    // Miscellaneous (2 patterns)
    PrefixValidationPattern {
        name: "adafruitio",
        prefix: "adafruitio_",
        tier: PatternTier::Services,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "1password-service-account-token",
        prefix: "1password-service-account-token_",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 300,
        charset: Charset::Any,
    },
    // Password Hashes (3 patterns)
    PrefixValidationPattern {
        name: "bcrypt-password-hash",
        prefix: "$2",
        tier: PatternTier::Infrastructure,
        min_len: 60,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "sha256-password-hash",
        prefix: "$5$",
        tier: PatternTier::Infrastructure,
        min_len: 50,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "sha512-password-hash",
        prefix: "$6$",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 200,
        charset: Charset::Base64,
    },
    // Database URI Patterns: REMOVED - These patterns cause false positives
    // Reason: Match "scheme://host:port" without detecting credentials (no colon for password)
    // Example false positives: "redis://localhost:6379", "postgres://db.example.com"
    // Solution: Use environment variable patterns instead (DATABASE_URL=, REDIS_URL=, etc.)
    // These env patterns catch real secrets and don't false positive on example URLs

    // Environment Variables (5 patterns)
    // DATABASE_URL & REDIS_URL: Fixed false positives on localhost/example URLs
    // Increased min_len to 40+ to avoid matching localhost examples
    // Real production connection strings with credentials are 50-100+ chars
    PrefixValidationPattern {
        name: "database-url-env",
        prefix: "DATABASE_URL=",
        tier: PatternTier::Critical,
        min_len: 50,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "redis-url-env",
        prefix: "REDIS_URL=",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 150,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "github-token-env",
        prefix: "GITHUB_TOKEN=ghp_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "docker-config-auth-env",
        prefix: "DOCKER_CONFIG_AUTH=",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 300,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "ssh-key-path-env",
        prefix: "SSH_KEY_PATH=/",
        tier: PatternTier::Infrastructure,
        min_len: 20,
        max_len: 500,
        charset: Charset::Any,
    },
    // Generic Environment Variable Patterns - REMOVED: OLD STRICT VERSIONS
    // These were replaced by more lenient versions below (min_len: 1) to catch
    // both short and long values. The old patterns required min_len: 15-20 which
    // was too strict for detecting all environment variable secrets.
    // Removed patterns:
    // - env-client-secret-suffix (prefix="_CLIENT_SECRET=", min_len: 20)
    // - env-api-key-suffix (prefix="_API_KEY=", min_len: 15)
    // - env-token-suffix (prefix="_TOKEN=", min_len: 20)
    // - env-secret-suffix (prefix="_SECRET=", min_len: 15)
    // - env-password-prefix (prefix="_PASSWORD=", min_len: 20)
    // - env-api-key-lowercase (prefix="api_key=", min_len: 15)
    // - env-client-secret-lowercase (prefix="client_secret=", min_len: 20)

    // Vault / Hashicorp (3 patterns)
    PrefixValidationPattern {
        name: "vault-api-token",
        prefix: "hvs.",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "vault-service-token",
        prefix: "s.",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "vault-batch-token",
        prefix: "b.",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Container & Orchestration (4 patterns)
    PrefixValidationPattern {
        name: "docker-swarm-token",
        prefix: "SWMTKN-",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "docker-api-key",
        prefix: "dckr_pat_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "kubernetes-bearer-token",
        prefix: "eyJhbGc",
        tier: PatternTier::Critical,
        min_len: 100,
        max_len: 300,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "docker-registry-token",
        prefix: "eyJ0eXAiOiJ",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 200,
        charset: Charset::Base64,
    },
    // Cloud Provider Config (3 patterns)
    PrefixValidationPattern {
        name: "aws-secret-env",
        prefix: "AWS_SECRET_ACCESS_KEY=",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "gcp-private-key-id",
        prefix: "private_key_id=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "azure-connection-string",
        prefix: "DefaultEndpointsProtocol=",
        tier: PatternTier::Critical,
        min_len: 50,
        max_len: 300,
        charset: Charset::Any,
    },
    // ============================================================================
    // BATCH 3: API Keys & Services (25 patterns)
    // Additional Database/Cache Services: REMOVED for false positive elimination
    // These patterns (dynamodb-uri, memcached-uri, couchdb-uri, influxdb-uri) caused false positives
    // Use environment variable patterns instead (DYNAMODB_URL=, etc.)

    // Communication Platforms (4 patterns)
    PrefixValidationPattern {
        name: "discord-bot-token",
        prefix: "ODI",
        tier: PatternTier::Infrastructure,
        min_len: 60,
        max_len: 300,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "telegram-token-env",
        prefix: "TELEGRAM_BOT_TOKEN=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slack-webhook-url",
        prefix: "https://hooks.slack.com/services/",
        tier: PatternTier::Infrastructure,
        min_len: 60,
        max_len: 300,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "zulip-api-key",
        prefix: "Zulip",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Development Tools & CI/CD (5 patterns)
    PrefixValidationPattern {
        name: "sonarqube-token",
        prefix: "squ_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "codecov-token",
        prefix: "codecov-token=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "buildkite-token",
        prefix: "bk_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "dependabot-token",
        prefix: "ghs_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sourcegraph-token",
        prefix: "sgp_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Analytics & Monitoring (4 patterns)
    PrefixValidationPattern {
        name: "datadog-api-key",
        prefix: "dd_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "amplitude-api-key",
        prefix: "amplitude-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mixpanel-api-token",
        prefix: "mixpanel_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Email & Message Services (3 patterns)
    PrefixValidationPattern {
        name: "sparkpost-api-key",
        prefix: "sparkpost-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sendpulse-api-token",
        prefix: "sendpulse-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mailerlite-api-key",
        prefix: "mailerlite-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Storage & CDN Services (3 patterns)
    PrefixValidationPattern {
        name: "digitalocean-spaces-key",
        prefix: "DO00",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "backblaze-b2-key",
        prefix: "b2_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wasabi-s3-key",
        prefix: "wasabi-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // ============================================================================
    // BATCH 4: Specialized Services & Cloud Platforms (25 patterns)
    // ============================================================================
    // AI/ML Platforms (5 patterns)
    PrefixValidationPattern {
        name: "replicate-api-token",
        prefix: "r8_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "anthropic-api-key",
        prefix: "sk-ant-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "mistral-api-key",
        prefix: "sk-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "together-api-key",
        prefix: "together-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "modal-token-env",
        prefix: "MODAL_TOKEN_ID=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Blockchain & Crypto (4 patterns)
    PrefixValidationPattern {
        name: "ethereum-private-key",
        prefix: "0x",
        tier: PatternTier::Critical,
        min_len: 66,
        max_len: 66,
        charset: Charset::Hex,
    },
    PrefixValidationPattern {
        name: "infura-api-key",
        prefix: "infura-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "alchemy-api-key",
        prefix: "alchemy-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "web3-storage-token",
        prefix: "eyJ",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 200,
        charset: Charset::Base64,
    },
    // Incident Management & Collaboration (4 patterns)
    PrefixValidationPattern {
        name: "victorops-api-key",
        prefix: "victorops-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "opsgenie-api-key",
        prefix: "opsgenie-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jira-api-token",
        prefix: "jira-api-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "linear-api-key",
        prefix: "lin_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Data & Search Platforms (4 patterns)
    PrefixValidationPattern {
        name: "algolia-api-key",
        prefix: "algolia-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "typesense-api-key",
        prefix: "typesense-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "meilisearch-api-key",
        prefix: "meili_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "weaviate-api-key",
        prefix: "weaviate-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Identity & Auth Platforms (4 patterns)
    PrefixValidationPattern {
        name: "auth0-management-token",
        prefix: "mgmt_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "auth0-client-secret",
        prefix: "client_secret=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // cognito-user-pool-id: REMOVED (false positives on cognito-idp:// URIs without credentials)
    PrefixValidationPattern {
        name: "keycloak-client-secret",
        prefix: "keycloak-secret=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Enterprise & SaaS Platforms (4 patterns)
    PrefixValidationPattern {
        name: "servicenow-api-key",
        prefix: "servicenow-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "salesforce-api-key",
        prefix: "salesforce-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "zendesk-api-token",
        prefix: "zendesk-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // supabase-postgres-password: REMOVED (false positives on postgres:// URIs like localhost, example.com)

    // ============================================================================
    // BATCH 5: Additional Providers & Niche Services (25 patterns)
    // ============================================================================
    // Game Development Platforms (4 patterns)
    PrefixValidationPattern {
        name: "unity-api-key",
        prefix: "unity-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "unreal-api-key",
        prefix: "unreal-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "godot-export-key",
        prefix: "godot-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "steam-api-key",
        prefix: "steam-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Documentation & Publishing (4 patterns)
    PrefixValidationPattern {
        name: "readme-io-api-key",
        prefix: "rdme_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "gitbook-api-token",
        prefix: "gbook_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "contentful-cpa-token",
        prefix: "CFPAT-",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "strapi-api-token",
        prefix: "strapi-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Automation & Workflow Platforms (5 patterns)
    PrefixValidationPattern {
        name: "zapier-api-key",
        prefix: "zapier-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "make-integration-token",
        prefix: "make_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "n8n-api-key",
        prefix: "n8n_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "workflow-automation-token",
        prefix: "wf_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "ifttt-webhook-key",
        prefix: "ifttt-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Design & Collaboration Tools (4 patterns)
    PrefixValidationPattern {
        name: "miro-api-token",
        prefix: "miro_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "lucidchart-api-key",
        prefix: "lucidchart-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "craft-api-token",
        prefix: "craft_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "invision-api-key",
        prefix: "invision-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Payment & Financial Services (3 patterns)
    PrefixValidationPattern {
        name: "square-access-token",
        prefix: "sq0atp-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wise-api-token",
        prefix: "wise_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "coinbase-api-key",
        prefix: "cb-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Quality Assurance & Testing (3 patterns)
    PrefixValidationPattern {
        name: "browserstack-api-key",
        prefix: "browserstack-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "testproject-io-token",
        prefix: "testproject_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "lambdatest-api-key",
        prefix: "lambdatest-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // ============================================================================
    // BATCH 6: Enterprise Tools & Monitoring Platforms (25 patterns)
    // ============================================================================
    // Application Performance Monitoring (5 patterns)
    PrefixValidationPattern {
        name: "new-relic-license-key",
        prefix: "NRJS-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "dynatrace-api-token",
        prefix: "dt0c01.",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "datadog-api-key-v2",
        prefix: "dda89f2d8b94f66",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Hex,
    },
    PrefixValidationPattern {
        name: "elastic-api-key",
        prefix: "elastic-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "splunk-hec-token",
        prefix: "splunk-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Logging & Log Aggregation (4 patterns)
    PrefixValidationPattern {
        name: "logz-io-api-token",
        prefix: "logz_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "papertrail-api-token",
        prefix: "papertrail-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sumo-logic-access-token",
        prefix: "sumo_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "loggly-api-token",
        prefix: "loggly-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Security & Vulnerability Management (4 patterns)
    PrefixValidationPattern {
        name: "snyk-api-token",
        prefix: "snyk_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "crowdstrike-api-token",
        prefix: "crowdstrike-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "qualys-api-token",
        prefix: "qualys-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "rapid7-api-key",
        prefix: "rapid7_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Cloud-Specific Tools (4 patterns)
    PrefixValidationPattern {
        name: "terraform-cloud-token",
        prefix: "api-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "pulumi-access-token",
        prefix: "pul-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "cloudsmith-api-key",
        prefix: "cloudsmith_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "artifactory-cloud-key",
        prefix: "AKCp",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Issue Tracking & Project Management (3 patterns)
    PrefixValidationPattern {
        name: "youtrack-api-token",
        prefix: "youtrack-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "taiga-api-token",
        prefix: "taiga_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "redmine-api-key",
        prefix: "redmine-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Container & Registry Services (3 patterns)
    PrefixValidationPattern {
        name: "quay-io-token",
        prefix: "quay_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "artifactory-helm-token",
        prefix: "AKCpD",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jfrog-xray-token",
        prefix: "xray-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Additional Enterprise Services (2 patterns)
    PrefixValidationPattern {
        name: "chef-api-token",
        prefix: "chef-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "puppet-api-token",
        prefix: "puppet-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // ============================================================================
    // BATCH 7: Final SaaS & Specialized Services (25 patterns)
    // ============================================================================
    // Productivity & Office Tools (4 patterns)
    PrefixValidationPattern {
        name: "airtable-api-token",
        prefix: "patU",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "notion-integration-token",
        prefix: "secret_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "confluence-api-token",
        prefix: "confluence_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "asana-api-token",
        prefix: "asana_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Real-Time Communication (4 patterns)
    PrefixValidationPattern {
        name: "twitch-oauth-token",
        prefix: "oauth-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "discord-webhook-url",
        prefix: "https://discord.com/api/webhooks/",
        tier: PatternTier::Infrastructure,
        min_len: 50,
        max_len: 500,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "matrix-homeserver-token",
        prefix: "syt_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "rocket-chat-token",
        prefix: "rocketchat-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Knowledge Management & Docs (3 patterns)
    PrefixValidationPattern {
        name: "confluence-cloud-token",
        prefix: "atc_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jira-cloud-token",
        prefix: "atb_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slite-api-token",
        prefix: "slite-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Marketplace & Integration Platforms (4 patterns)
    PrefixValidationPattern {
        name: "shopify-api-key",
        prefix: "shppa_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wix-api-token",
        prefix: "wix_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "bigcommerce-api-token",
        prefix: "bigcommerce-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "intercom-access-token",
        prefix: "intercom-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Social Media & Content (3 patterns)
    PrefixValidationPattern {
        name: "instagram-business-token",
        prefix: "IGQWRN",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 200,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "tiktok-api-token",
        prefix: "tiktok-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "youtube-api-key",
        prefix: "AIza",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // Analytics & Data (2 patterns)
    PrefixValidationPattern {
        name: "segment-write-key",
        prefix: "segment-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "chartio-api-token",
        prefix: "chartio-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // Additional Specialized Services (2 patterns)
    PrefixValidationPattern {
        name: "fastapi-key",
        prefix: "fk_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "graphql-api-token",
        prefix: "gql_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 200,
        charset: Charset::Alphanumeric,
    },
    // ===== TIER 1 DATABASE & INFRASTRUCTURE (6 patterns) =====
    // MySQL official password environment variable
    PrefixValidationPattern {
        name: "mysql-password-env",
        prefix: "MYSQL_PWD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // RabbitMQ default password environment variable (standard in Docker)
    PrefixValidationPattern {
        name: "rabbitmq-default-pass-env",
        prefix: "RABBITMQ_DEFAULT_PASS=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Redis password environment variable
    PrefixValidationPattern {
        name: "redis-password-env",
        prefix: "REDIS_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // PostgreSQL root password (different from PGPASSWORD which is for client connections)
    PrefixValidationPattern {
        name: "postgres-root-password-env",
        prefix: "POSTGRES_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Docker Registry password for authentication (CI/CD)
    PrefixValidationPattern {
        name: "docker-registry-password-env",
        prefix: "DOCKER_REGISTRY_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // HashiCorp Vault token (auth token enables full vault access)
    PrefixValidationPattern {
        name: "vault-token-env",
        prefix: "VAULT_TOKEN=",
        tier: PatternTier::Critical,
        min_len: 20,
        max_len: 200,
        charset: Charset::Base64Url,
    },
    // ===== TIER 2 ENTERPRISE & SPECIALIZED SERVICES (9 patterns) =====
    // LDAP directory service password
    PrefixValidationPattern {
        name: "ldap-password-env",
        prefix: "LDAP_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // LDAP bind password (service account authentication)
    PrefixValidationPattern {
        name: "ldap-bind-password-env",
        prefix: "LDAP_BIND_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Apache Cassandra NoSQL database password
    PrefixValidationPattern {
        name: "cassandra-password-env",
        prefix: "CASSANDRA_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Elasticsearch search engine password
    PrefixValidationPattern {
        name: "elasticsearch-password-env",
        prefix: "ELASTICSEARCH_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Apache CouchDB document database password
    PrefixValidationPattern {
        name: "couchdb-password-env",
        prefix: "COUCHDB_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Apache Kafka SASL authentication password
    PrefixValidationPattern {
        name: "kafka-sasl-password-env",
        prefix: "KAFKA_SASL_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Apache ActiveMQ message broker password
    PrefixValidationPattern {
        name: "activemq-password-env",
        prefix: "ACTIVEMQ_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Bitbucket Git server password (for CI/CD authentication)
    PrefixValidationPattern {
        name: "bitbucket-password-env",
        prefix: "BITBUCKET_PASSWORD=",
        tier: PatternTier::Infrastructure,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // SMTP mail server password (email authentication)
    PrefixValidationPattern {
        name: "smtp-password-env",
        prefix: "SMTP_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 15,
        max_len: 100,
        charset: Charset::Any,
    },
    // Generic environment variable KEY=VALUE patterns (hardcoded for common naming conventions)
    // These are added to catch PASSWORD=, SECRET=, TOKEN=, API_KEY=, APIKEY= in various forms
    // with auto-generated variations (exact, prefix, suffix)

    // PASSWORD variations
    PrefixValidationPattern {
        name: "env-password",
        prefix: "PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-password-prefix-lenient",
        prefix: "_PASSWORD=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-password-suffix",
        prefix: "PASSWORD_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    // SECRET variations
    PrefixValidationPattern {
        name: "env-secret",
        prefix: "SECRET=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-secret-prefix-lenient",
        prefix: "_SECRET=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-secret-suffix",
        prefix: "SECRET_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    // TOKEN variations
    PrefixValidationPattern {
        name: "env-token",
        prefix: "TOKEN=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-token-prefix-lenient",
        prefix: "_TOKEN=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-token-suffix",
        prefix: "TOKEN_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    // API_KEY variations
    PrefixValidationPattern {
        name: "env-api-key",
        prefix: "API_KEY=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-api-key-prefix-lenient",
        prefix: "_API_KEY=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-api-key-suffix",
        prefix: "API_KEY_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    // APIKEY variations (no underscore)
    PrefixValidationPattern {
        name: "env-apikey",
        prefix: "APIKEY=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-apikey-prefix",
        prefix: "_APIKEY=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-apikey-suffix",
        prefix: "APIKEY_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    // PASSPHRASE variations
    PrefixValidationPattern {
        name: "env-passphrase",
        prefix: "PASSPHRASE=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-passphrase-prefix-lenient",
        prefix: "_PASSPHRASE=",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "env-passphrase-suffix",
        prefix: "PASSPHRASE_",
        tier: PatternTier::Critical,
        min_len: 1,
        max_len: 500,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "bcrypt-password-hash",
        prefix: "$2", // $2a, $2y, $2x variants
        tier: PatternTier::Infrastructure,
        min_len: 60, // Bcrypt hashes are always 60 chars
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "sha256-password-hash",
        prefix: "$5$",
        tier: PatternTier::Infrastructure,
        min_len: 50,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "sha512-password-hash",
        prefix: "$6$",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "redis-url-env",
        prefix: "REDIS_URL=",
        tier: PatternTier::Critical,
        min_len: 20,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "github-token-env",
        prefix: "GITHUB_TOKEN=ghp_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "docker-config-auth-env",
        prefix: "DOCKER_CONFIG_AUTH=",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "ssh-key-path-env",
        prefix: "SSH_KEY_PATH=/",
        tier: PatternTier::Infrastructure,
        min_len: 20,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "vault-api-token",
        prefix: "hvs.",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "vault-service-token",
        prefix: "s.",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "vault-batch-token",
        prefix: "b.",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "docker-swarm-token",
        prefix: "SWMTKN-",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "docker-api-key",
        prefix: "dckr_pat_",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "kubernetes-bearer-token",
        prefix: "eyJhbGc", // Base64 for JWT header {"alg"
        tier: PatternTier::Critical,
        min_len: 100,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "docker-registry-token",
        prefix: "eyJ0eXAiOiJ", // Base64 for JWT header {"typ":"JWT"
        tier: PatternTier::Critical,
        min_len: 100,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "aws-secret-env",
        prefix: "AWS_SECRET_ACCESS_KEY=",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "gcp-private-key-id",
        prefix: "private_key_id=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "azure-connection-string",
        prefix: "DefaultEndpointsProtocol=",
        tier: PatternTier::Critical,
        min_len: 50,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "discord-bot-token",
        prefix: "ODI", // Base64 for bot token format
        tier: PatternTier::Infrastructure,
        min_len: 60,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "telegram-token-env",
        prefix: "TELEGRAM_BOT_TOKEN=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "zulip-api-key",
        prefix: "Zulip", // Zulip tokens often start with "Zulip"
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sonarqube-token",
        prefix: "squ_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "codecov-token",
        prefix: "codecov-token=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "buildkite-token",
        prefix: "bk_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "dependabot-token",
        prefix: "ghs_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sourcegraph-token",
        prefix: "sgp_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "datadog-api-key",
        prefix: "dd_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sentry-dsn-url",
        prefix: "https://",
        tier: PatternTier::Infrastructure,
        min_len: 50,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "amplitude-api-key",
        prefix: "amplitude-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mixpanel-api-token",
        prefix: "mixpanel_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sparkpost-api-key",
        prefix: "sparkpost-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sendpulse-api-token",
        prefix: "sendpulse-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "mailerlite-api-key",
        prefix: "mailerlite-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "digitalocean-spaces-key",
        prefix: "DO00", // Base64 encoding of DO token
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "backblaze-b2-key",
        prefix: "b2_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wasabi-s3-key",
        prefix: "wasabi-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "replicate-api-token",
        prefix: "r8_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "anthropic-api-key",
        prefix: "sk-ant-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "mistral-api-key",
        prefix: "sk-", // Mistral keys use sk- prefix
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "together-api-key",
        prefix: "together-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "modal-token-env",
        prefix: "MODAL_TOKEN_ID=",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "ethereum-private-key",
        prefix: "0x",
        tier: PatternTier::Critical,
        min_len: 66, // 0x + 64 hex chars
        max_len: 66,
        charset: Charset::Hex,
    },
    PrefixValidationPattern {
        name: "infura-api-key",
        prefix: "infura-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "alchemy-api-key",
        prefix: "alchemy-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "web3-storage-token",
        prefix: "eyJ", // Base64 for JWT header
        tier: PatternTier::Critical,
        min_len: 100,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "victorops-api-key",
        prefix: "victorops-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "opsgenie-api-key",
        prefix: "opsgenie-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jira-api-token",
        prefix: "jira-api-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "linear-api-key",
        prefix: "lin_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "algolia-api-key",
        prefix: "algolia-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "typesense-api-key",
        prefix: "typesense-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "meilisearch-api-key",
        prefix: "meili_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "weaviate-api-key",
        prefix: "weaviate-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "auth0-management-token",
        prefix: "mgmt_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "auth0-client-secret",
        prefix: "client_secret=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "cognito-user-pool-id",
        prefix: "cognito-idp://",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "keycloak-client-secret",
        prefix: "keycloak-secret=",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "servicenow-api-key",
        prefix: "servicenow-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "salesforce-api-key",
        prefix: "salesforce-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "zendesk-api-token",
        prefix: "zendesk-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "supabase-postgres-password",
        prefix: "postgres://",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Any,
    },
    PrefixValidationPattern {
        name: "unity-api-key",
        prefix: "unity-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "unreal-api-key",
        prefix: "unreal-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "godot-export-key",
        prefix: "godot-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "steam-api-key",
        prefix: "steam-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "readme-io-api-key",
        prefix: "rdme_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "gitbook-api-token",
        prefix: "gbook_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "contentful-cpa-token",
        prefix: "CFPAT-",
        tier: PatternTier::Infrastructure,
        min_len: 40,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "strapi-api-token",
        prefix: "strapi-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "zapier-api-key",
        prefix: "zapier-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "make-integration-token",
        prefix: "make_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "n8n-api-key",
        prefix: "n8n_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "workflow-automation-token",
        prefix: "wf_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "ifttt-webhook-key",
        prefix: "ifttt-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "miro-api-token",
        prefix: "miro_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "lucidchart-api-key",
        prefix: "lucidchart-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "craft-api-token",
        prefix: "craft_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "invision-api-key",
        prefix: "invision-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "square-access-token",
        prefix: "sq0atp-",
        tier: PatternTier::Critical,
        min_len: 40,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wise-api-token",
        prefix: "wise_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "coinbase-api-key",
        prefix: "cb-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "browserstack-api-key",
        prefix: "browserstack-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "testproject-io-token",
        prefix: "testproject_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "lambdatest-api-key",
        prefix: "lambdatest-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "new-relic-license-key",
        prefix: "NRJS-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "dynatrace-api-token",
        prefix: "dt0c01.",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "datadog-api-key-v2",
        prefix: "dda89f2d8b94f66", // Datadog specific format
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Hex,
    },
    PrefixValidationPattern {
        name: "elastic-api-key",
        prefix: "elastic-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "splunk-hec-token",
        prefix: "splunk-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "logz-io-api-token",
        prefix: "logz_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "papertrail-api-token",
        prefix: "papertrail-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "sumo-logic-access-token",
        prefix: "sumo_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "loggly-api-token",
        prefix: "loggly-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "snyk-api-token",
        prefix: "snyk_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "crowdstrike-api-token",
        prefix: "crowdstrike-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "qualys-api-token",
        prefix: "qualys-",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "rapid7-api-key",
        prefix: "rapid7_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "terraform-cloud-token",
        prefix: "api-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "pulumi-access-token",
        prefix: "pul-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "cloudsmith-api-key",
        prefix: "cloudsmith_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "artifactory-cloud-key",
        prefix: "AKCp",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "youtrack-api-token",
        prefix: "youtrack-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "taiga-api-token",
        prefix: "taiga_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "redmine-api-key",
        prefix: "redmine-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "quay-io-token",
        prefix: "quay_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "artifactory-helm-token",
        prefix: "AKCpD",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jfrog-xray-token",
        prefix: "xray-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "chef-api-token",
        prefix: "chef-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "puppet-api-token",
        prefix: "puppet-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "airtable-api-token",
        prefix: "patU",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "notion-integration-token",
        prefix: "secret_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "confluence-api-token",
        prefix: "confluence_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "asana-api-token",
        prefix: "asana_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "twitch-oauth-token",
        prefix: "oauth-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "matrix-homeserver-token",
        prefix: "syt_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "rocket-chat-token",
        prefix: "rocketchat-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "confluence-cloud-token",
        prefix: "atc_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "jira-cloud-token",
        prefix: "atb_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "slite-api-token",
        prefix: "slite-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "shopify-api-key",
        prefix: "shppa_",
        tier: PatternTier::Critical,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "wix-api-token",
        prefix: "wix_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "bigcommerce-api-token",
        prefix: "bigcommerce-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "intercom-access-token",
        prefix: "intercom-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "instagram-business-token",
        prefix: "IGQWRN",
        tier: PatternTier::Infrastructure,
        min_len: 100,
        max_len: 0,
        charset: Charset::Base64,
    },
    PrefixValidationPattern {
        name: "tiktok-api-token",
        prefix: "tiktok-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "youtube-api-key",
        prefix: "AIza",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Base64Url,
    },
    PrefixValidationPattern {
        name: "segment-write-key",
        prefix: "segment-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "chartio-api-token",
        prefix: "chartio-",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "fastapi-key",
        prefix: "fk_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
    PrefixValidationPattern {
        name: "graphql-api-token",
        prefix: "gql_",
        tier: PatternTier::Infrastructure,
        min_len: 30,
        max_len: 0,
        charset: Charset::Alphanumeric,
    },
];
